### PR TITLE
improve Declaration of Genesis section

### PR DESCRIPTION
**Pull request by stevenoruzi**

### CODE REVIEW

**Comment by jaekwon** [comment]
Hi it looks like you merged the constitution into and replaced the original README file. (see "files changed" tab in github).
I do see the changes in this commit, and it seems sufficient: https://github.com/atomone-hub/genesis/pull/2/commits/817e3c8e3e63acb03e45cafdc230a73eb744a885 ?

**Comment by stevenoruzi** [comment]
let me rebase it with the main. I will update it

**Comment by stevenoruzi** [comment]
@jaekwon plz review it. 
I tried to improve the Declaration of Genesis. will check the rest tomorrow.

**Comment by jaekwon** [comment]
looks great thank you lets iterate!

**Pull request merged**
